/** ENVIRONMENT */
export const SETUP_ENVIRONMENT = 'SETUP_ENVIRONMENT';

/** TOKEN */
export const STORE_DEVICE_TOKEN = 'STORE_DEVICE_TOKEN';

/** LOCALE */
export const CHANGE_DEVICE_LOCALE = 'CHANGE_DEVICE_LOCALE';

/** CHAT_COLOR */
export const CHANGE_CHAT_COLOR = 'CHANGE_CHAT_COLOR';

/** ONBOARDING SCREEN */
export const HIDE_ONBOARDING = 'HIDE_ONBOARDING';

/** ALERT DIALOG */
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

/** THEME MODE */
export const SWITCH_THEME_MODE = 'SWITCH_THEME_MODE';

/** SOCKET */
export const SOCKET_INSTANCE = 'SOCKET_INSTANCE';
