/** ENVIRONMENT */
export const SETUP_ENVIRONMENT = 'SETUP_ENVIRONMENT';

/** TOKEN */
export const STORE_DEVICE_TOKEN = 'STORE_DEVICE_TOKEN';

/** LOCALE */
export const CHANGE_DEVICE_LOCALE = 'CHANGE_DEVICE_LOCALE';

/** ONBOARDING SCREEN */
export const HIDE_ONBOARDING = 'HIDE_ONBOARDING';

/** ALERT DIALOG */
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
