export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';

export const GET_MESSAGES = 'GET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const NEW_MESSAGES_COMING = 'NEW_MESSAGES_COMING';
export const TYPING_LISTENING = 'TYPING_LISTENING';
