import {MOMENTS} from '@assets';
import {IMOMENT} from '@screens/Bottom/Moments/types';

export const DATA: IMOMENT[] = [
  {
    id: 1,
    image: MOMENTS.moment1,
    title: 'Ha Giang Travel, first month in Vietnam',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 2,
    image: MOMENTS.moment2,
    title: 'Jeru',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 3,
    image: MOMENTS.moment3,
    title: 'Harvesting rice fields with my mom',
    loved: true,
    author: '@jacknguyen',
  },
  {
    id: 4,
    image: MOMENTS.moment4,
    title: 'Keep body clean with MedianCare',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 5,
    image: MOMENTS.moment5,
    title: '',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 6,
    image: MOMENTS.moment6,
    title: 'I don’t think bar club is  better than this..',
    loved: false,
    author: '@author',
  },
  {
    id: 7,
    image: MOMENTS.moment7,
    title: '',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 8,
    image: MOMENTS.moment8,
    title: 'My cat fixed me!',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 9,
    image: MOMENTS.moment9,
    title: 'Today I drew a paint of lavender',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 10,
    image: MOMENTS.moment3,
    title: '',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 11,
    image: MOMENTS.moment7,
    title: 'My cat fixed me!',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 12,
    image: MOMENTS.moment4,
    title: 'Today I drew a paint of lavender',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 13,
    image: MOMENTS.moment9,
    title: 'Today I drew a paint of lavender',
    loved: false,
    author: '@jacknguyen',
  },
];
