import {DISCOVER} from '@assets';
import {INEWSFEED} from '@screens/Bottom/Discover/types';

export const DATA: INEWSFEED[] = [
  {
    id: 1,
    image: DISCOVER.discover1,
    title: 'Ha Giang Travel, first month in Vietnam',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 2,
    image: DISCOVER.discover2,
    title: 'Jeru',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 3,
    image: DISCOVER.discover3,
    title: 'Harvesting rice fields with my mom',
    loved: true,
    author: '@jacknguyen',
  },
  {
    id: 4,
    image: DISCOVER.discover4,
    title: 'Keep body clean with MedianCare',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 5,
    image: DISCOVER.discover5,
    title: '',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 6,
    image: DISCOVER.discover6,
    title: 'I don’t think bar club is  better than this..',
    loved: false,
    author: '@author',
  },
  {
    id: 7,
    image: DISCOVER.discover7,
    title: '',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 8,
    image: DISCOVER.discover8,
    title: 'My cat fixed me!',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 9,
    image: DISCOVER.discover9,
    title: 'Today I drew a paint of lavender',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 10,
    image: DISCOVER.discover3,
    title: '',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 11,
    image: DISCOVER.discover7,
    title: 'My cat fixed me!',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 12,
    image: DISCOVER.discover4,
    title: 'Today I drew a paint of lavender',
    loved: false,
    author: '@jacknguyen',
  },
  {
    id: 13,
    image: DISCOVER.discover9,
    title: 'Today I drew a paint of lavender',
    loved: false,
    author: '@jacknguyen',
  },
];
