export const CREATE_MILESTONE = 'CREATE_MILESTONE';
export const GET_MILESTONES = 'GET_MILESTONES';
export const GET_MILESTONE_DETAILS = 'GET_MILESTONE_DETAILS';
export const UPDATE_MILESTONE = 'UPDATE_MILESTONE';
