export const STORE_REGISTER_DATA = 'STORE_REGISTER_DATA';
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const LOGOUT_ACCOUNT = 'LOGOUT_ACCOUNT';
