export const GET_USER_MOMENTS_LIST = 'GET_USER_MOMENTS_LIST';
export const CREATE_MOMENT = 'CREATE_MOMENT';
export const GET_MOMENT_DETAILS = 'GET_MOMENT_DETAILS';
export const SET_ACTIVE_MOMENT = 'SET_ACTIVE_MOMENT';
export const EDIT_MOMENT = 'EDIT_MOMENT';
export const DELETE_MOMENT = 'DELETE_MOMENT';
