export const ICONS = {
  arrow_down: require('./icons/arrow_down.png'),
  arrow_left: require('./icons/arrow_left.png'),
  arrow_right: require('./icons/arrow_right.png'),
  arrow_up: require('./icons/arrow_up.png'),
  image_holder: require('./icons/image_holder.png'),
  close: require('./icons/close.png'),
  checkbox: require('./icons/checkbox.png'),
  plus: require('./icons/plus.png'),
  apple: require('./icons/apple.png'),
  google: require('./icons/google.png'),
  twitter: require('./icons/twitter.png'),
  back: require('./icons/back.png'),
  calendar: require('./icons/calendar.png'),
  bottom_chat: require('./icons/bottom_chat.png'),
  bottom_feeds: require('./icons/bottom_feeds.png'),
  bottom_gadgets: require('./icons/bottom_gadgets.png'),
  bottom_home: require('./icons/bottom_home.png'),
  bottom_chat_selected: require('./icons/bottom_chat_selected.png'),
  bottom_feeds_selected: require('./icons/bottom_feeds_selected.png'),
  bottom_gadgets_selected: require('./icons/bottom_gadgets_selected.png'),
  bottom_home_selected: require('./icons/bottom_home_selected.png'),
  eye_closed: require('./icons/eye_closed.png'),
  eye_open: require('./icons/eye_open.png'),
  send: require('./icons/send.png'),
  received_msg: require('./icons/received_msg.png'),
  sent_msg: require('./icons/sent_msg.png'),
  edit: require('./icons/edit.png'),
  camera: require('./icons/camera.png'),
  image: require('./icons/image.png'),
  voice: require('./icons/voice.png'),
  gadget_apps: require('./icons/gadget_apps.png'),
  gadget_customization: require('./icons/gadget_customization.png'),
  gadget_feedback: require('./icons/gadget_feedback.png'),
  gadget_mood_history: require('./icons/gadget_mood_history.png'),
  logout: require('./icons/logout.png'),
};

export const IMAGES = {
  logo: require('./images/logo.png'),
  splash_logo: require('./images/splash_logo.png'),
  error: require('./images/error.png'),
  info: require('./images/info.png'),
  success: require('./images/success.png'),
  warning: require('./images/warning.png'),
  story1: require('./images/story1.jpg'),
  story2: require('./images/story2.jpg'),
  article1: require('./images/article1.png'),
  boring: require('./images/boring.png'),
  fun: require('./images/fun.png'),
  sad: require('./images/sad.png'),
  stress: require('./images/stress.png'),
  avatar: require('./images/avatar.png'),
  community: require('./images/community.png'),
  exchange: require('./images/exchange.png'),
  game: require('./images/game.png'),
  market: require('./images/market.png'),
  music: require('./images/music.png'),
  shopping: require('./images/shopping.png'),
  logout_icon_left: require('./images/logout_icon_left.png'),
  logout_icon_right: require('./images/logout_icon_right.png'),
};

export const MILESTONE = {
  milestone1: require('./milestones/milestone1.png'),
  milestone2: require('./milestones/milestone2.png'),
  milestone3: require('./milestones/milestone3.png'),
  milestone4: require('./milestones/milestone4.png'),
  milestone5: require('./milestones/milestone5.png'),
  milestone6: require('./milestones/milestone6.png'),
  milestone7: require('./milestones/milestone7.png'),
  milestone8: require('./milestones/milestone8.png'),
  milestone9: require('./milestones/milestone9.png'),
  milestone10: require('./milestones/milestone10.png'),
  milestone11: require('./milestones/milestone11.png'),
};
