const routes = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  /*__auth__*/
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_STEP1_SCREEN: 'REGISTER_STEP1_SCREEN',
  REGISTER_STEP2_SCREEN: 'REGISTER_STEP2_SCREEN',
  REGISTER_STEP3_SCREEN: 'REGISTER_STEP3_SCREEN',
  REGISTER_STEP4_SCREEN: 'REGISTER_STEP4_SCREEN',
  REGISTER_STEP5_SCREEN: 'REGISTER_STEP5_SCREEN',
  FORGOT_PASSWORD_STEP1_SCREEN: 'FORGOT_PASSWORD_STEP1_SCREEN',
  FORGOT_PASSWORD_STEP2_SCREEN: 'FORGOT_PASSWORD_STEP2_SCREEN',
  FORGOT_PASSWORD_STEP3_SCREEN: 'FORGOT_PASSWORD_STEP3_SCREEN',
  FORGOT_PASSWORD_STEP4_SCREEN: 'FORGOT_PASSWORD_STEP4_SCREEN',
  /*__common__*/
};

export default routes;
