const routes = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  /*__auth__*/
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_STEP1_SCREEN: 'REGISTER_STEP1_SCREEN',
  REGISTER_STEP2_SCREEN: 'REGISTER_STEP2_SCREEN',
  REGISTER_STEP3_SCREEN: 'REGISTER_STEP3_SCREEN',
  REGISTER_STEP4_SCREEN: 'REGISTER_STEP4_SCREEN',
  REGISTER_STEP5_SCREEN: 'REGISTER_STEP5_SCREEN',
  FORGOT_PASSWORD_STEP1_SCREEN: 'FORGOT_PASSWORD_STEP1_SCREEN',
  FORGOT_PASSWORD_STEP2_SCREEN: 'FORGOT_PASSWORD_STEP2_SCREEN',
  FORGOT_PASSWORD_STEP3_SCREEN: 'FORGOT_PASSWORD_STEP3_SCREEN',
  FORGOT_PASSWORD_STEP4_SCREEN: 'FORGOT_PASSWORD_STEP4_SCREEN',
  /*__bottom__*/
  FEEDS_SCREEN: 'FEEDS_SCREEN',
  CHAT_SCREEN: 'CHAT_SCREEN',
  GADGETS_SCREEN: 'GADGETS_SCREEN',
  /*__bottom_home_stack__*/
  BOTTOM_HOME_STACK: 'BOTTOM_HOME_STACK',
  HOME_SCREEN: 'HOME_SCREEN',
  MILESTONE_DETAILS_SCREEN: 'MILESTONE_DETAILS_SCREEN',
  /*__common__*/
  ARTICLE_DETAILS_SCREEN: 'ARTICLE_DETAILS_SCREEN',
} as const;

export default routes;
